{% set name = "ubiquerg" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b4094377061fd5425cfc9f10865437f2c01d90a0d933d08682d789dc3e4ece8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - hatchling
    - python >=3.10
  run:
    - python >=3.10

test:
  imports:
    - ubiquerg

about:
  home: https://github.com/pepkit/ubiquerg
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Various utility functions.

extra:
  recipe-maintainers:
    - stolarczyk
    - nsheff
