{% set name = "ubiquerg" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4cc97356c99a1b5000a6869d43165da35a64dbd36f7c710fd17a47613a3a65e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python
    - veracitools

test:
  imports:
    - ubiquerg

about:
  home: https://github.com/pepkit/ubiquerg
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Various utility functions.

extra:
  recipe-maintainers:
    - michalstolarczyk
