{% set name = "ubiquerg" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 734de66e1412f07196b30f44965e43dfe56bda7585b7eece33edffb47dff8422

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - hatchling
    - python >=3.10
  run:
    - python >=3.10

test:
  imports:
    - ubiquerg

about:
  home: https://github.com/pepkit/ubiquerg
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Various utility functions.

extra:
  recipe-maintainers:
    - stolarczyk
    - nsheff
